# Generated by Django 4.0.4 on 2022-05-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_student_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('block_name',)},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='floor_id',
            new_name='floor',
        ),
        migrations.RemoveField(
            model_name='block',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='floor_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='block',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booking.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='course',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0, verbose_name='Course year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='faculty',
            field=models.CharField(choices=[('Faculty of Law and Social Sciences', 'Faculty of Law and Social Sciences'), ('Faculty of Education and Humanities Sciences', 'Faculty of Education and Humanities Sciences'), ('Faculty of Engineering and Natural Sciences', 'Faculty of Engineering and Natural Sciences'), ('Business school', 'Business school')], default=3, max_length=100, verbose_name='Faculty name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=True, max_length=100, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
