# Generated by Django 4.0.4 on 2022-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Faculty of Law and Social Sciences', 'Faculty of Law and Social Sciences'), ('Faculty of Education and Humanities Sciences', 'Faculty of Education and Humanities Sciences'), ('Faculty of Engineering and Natural Sciences', 'Faculty of Engineering and Natural Sciences'), ('Business school', 'Business school')], max_length=50, null=True, verbose_name='Faculty name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True, verbose_name='Gender'),
        ),
    ]
