# Generated by Django 4.0.4 on 2022-05-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_student_email_alter_student_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
