# Generated by Django 4.0.4 on 2022-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
