# Generated by Django 4.0.4 on 2022-05-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_check_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_number',
            field=models.IntegerField(default=True, verbose_name='Bed number'),
            preserve_default=False,
        ),
    ]
